# Generated by Django 5.0.6 on 2024-06-14 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('forename', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=30)),
                ('sample_number', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=30)),
                ('lab_no', models.CharField(max_length=30)),
                ('sample_dated', models.DateTimeField()),
                ('sample_received', models.DateTimeField()),
                ('result_reported', models.DateTimeField()),
                ('sample_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['forename', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'verbose_name': 'Summary',
                'verbose_name_plural': 'Summaries',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('reference_range', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'verbose_name': 'TestResult',
                'verbose_name_plural': 'TestResults',
                'ordering': ['test_name'],
            },
        ),
    ]
