# Generated by Django 5.0.6 on 2024-06-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='reference_max',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='reference_min',
        ),
        migrations.AddField(
            model_name='testresult',
            name='ref_range',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
